### ISSUE TITLE
A bug when I run the script run_experiment.py with default args

### ISSUE THREAD

**Issue by CuiZhiying** [Khurramjaved96/iCarl2.0#3]
hello，when I want to reuse the code, I get an error that I can not find out what's wrong, The complete error is as follow, all the args remain default
![image](https://user-images.githubusercontent.com/16770471/51371306-c80c2800-1b34-11e9-9c1e-8d7b8247c6ec.png)

**Comment by kjaved0** [comment]
The error was caused by a change in when PyTorch's dataloader verifies size of data > 0. I've fixed the issue and pushed the changes.

**Comment by CuiZhiying** [comment]
I try it again, and it works well. Thank you very much!

Khurram Javed <notifications@github.com> 于2019年1月22日周二 上午4:11写道：
